# Generated by Django 5.0 on 2023-12-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0002_alter_boathistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
